zookeeper:
  image: linkerrepository/zookeeper
  net: "host"
  command: /init.sh
  env_file: .env
  environment:
 #  - "constraint:master==true"
   - "affinity:container!=*zookeeper*"

mesosmaster:
  image: linkerrepository/mesos-master
  net: "host"
  command: /entrypoint.sh
  env_file: .env
  environment:
   - MESOS_LOG_DIR=/var/log/mesos
   - MESOS_QUORUM=2
   - MESOS_REGISTRY=in_memory
   - MESOS_WORK_DIR=/var/lib/mesos
#   - "constraint:master==true"
   - "affinity:container!=*mesosmaster*"

marathon:
  image: linkerrepository/marathon
  net: "host"
  command: /entrypoint.sh
  env_file: .env
  environment:
#   - "constraint:master==true"
   - "affinity:container!=*marathon*"


mesosslave:
  image: linkerrepository/mesos-slave
  volumes:
   - /sys/fs/cgroup:/sys/fs/cgroup
   - /var/run/docker.sock:/var/run/docker.sock
  net: "host"
  command: /entrypoint.sh
  env_file: .env
  environment:
   - MESOS_CONTAINERIZERS=docker
   - MESOS_LOG_DIR=/var/log/mesos
   - MESOS_LOGGING_LEVEL=INFO
 #  - "constraint:slave==true"
   - "affinity:container!=*mesosslave*"

